### ISSUE TITLE
Params could also specify ini file to load

### ISSUE THREAD

**Issue by mryellow** [romainreignier/rtimulib_ros#1]
https://github.com/romainreignier/rtimulib_ros/blob/master/src/rtimulib_ros.cpp#L50

Like how you've left everything in the ini files however when using multiple IMU, multiple directories are needed. Would be nice if both the path and 'productType' could be specified separately.

This would enable separate ini files in the same directory.

**Comment by romainreignier** [comment]
I see how to create a separate directory for each device.
But what do you mean by specifying the productType ? I don't see that point.
Thanks

**Comment by mryellow** [comment]
The `RTIMUSettings::RTIMUSettings(const char *settingsDirectory, const char *productType)` signature `productType` ends up as the [ini file being used](https://github.com/RTIMULib/RTIMULib/blob/7619c9b93d75a7b938027e819a3a10d0fb60959c/RTIMULib/RTIMUSettings.cpp#L63).

Separate directories is nice as you can run the `RTIMULibCal` util in each and not worry about it any further. Single directory would be nice for those who don't want a separate directory for each. They'd run the calibration tool with parameters specifying the [output ini filename](https://github.com/RTIMULib/RTIMULib/blob/7619c9b93d75a7b938027e819a3a10d0fb60959c/Linux/RTIMULibCal/RTIMULibCal.cpp#L73).

**Comment by romainreignier** [comment]
Ok, thanks. I see.
I will add that !

**Comment by romainreignier** [comment]
I have added custom productType argument by using a `calibration_file_name` argument.
Let me know if it is what you want.

**Comment by mryellow** [comment]
Looks good. Quick to configure without having to put params in yaml like `i2c_imu` package.

```
process[kulbu/imu0-1]: started with pid [2326]
[ INFO] [1435983695.878301763]: Imu driver is now running
Settings file /home/odroid/ros/ws/src/kulbu_hardware/config/imu0.ini loaded
Using fusion algorithm RTQF
Using min/max compass calibration
Ellipsoid compass calibration not in use
Using accel calibration
GD20HM303DLHC init complete
process[kulbu/imu1-2]: started with pid [2342]
[ INFO] [1435983696.360327564]: Imu driver is now running
Settings file /home/odroid/ros/ws/src/kulbu_hardware/config/imu1.ini loaded
Using fusion algorithm RTQF
Using min/max compass calibration
Ellipsoid compass calibration not in use
Using accel calibration
MPU9150 init complete
```
