### ISSUE TITLE
NED or ENU

### ISSUE THREAD

**Issue by spcrobocar** [romainreignier/rtimulib_ros#11]
Is the coordinates system of the IMU pose from this repo NED or ENU?

**Comment by romainreignier** [comment]
Hi,
There is an attempt to convert to ENU coordinates, given that the IMU sensor is using NED:
https://github.com/romainreignier/rtimulib_ros/blob/2aa8624bde1d20582c53d45b84f6e55de9961fc4/src/rtimulib_ros.cpp#L99

But it might not always work or worse, the conversion might be faulty.
Did you face any specific issue?

**Comment by spcrobocar** [comment]
So the ROS output is in ENU. But want to confirm.

**Comment by romainreignier** [comment]
Yes, it should be
