### ISSUE TITLE
Params scope is fixed

### ISSUE THREAD

**Issue by mryellow** [romainreignier/rtimulib_ros#2]
With `/rtimulib_node` prepended to the reading of parameters, node breaks down when put into new namespaces.

**Comment by romainreignier** [comment]
Hi, thanks for your interest of my package.
I will see how to change the use of parameter to be able to change the node name and the namespace. You're right, it is a real issue.
I won't be able to do this this week. Maybe next week.
If you have an idea how to do that, a PR is welcomed :)

**Comment by romainreignier** [comment]
The node name and namespace should not break the reading of parameters anymore now.
Let me know if it is ok for you.

**Comment by mryellow** [comment]
I'm going to have to read up on these myself, not sure what the difference is there with private params, thought it was simply a matter of the path. Will give it a test shortly.

edit: So they are "semi-private", still accessible elsewhere but inside the namespace... Interesting that they get an `_` prefix when specified on command-line. heh notice it's actually how a lot of nodes work, never really took note of it before.

**Comment by mryellow** [comment]
All works as expected.

```
    <node name="imu0" pkg="rtimulib_ros" type="rtimulib_ros"
          output="screen">
        <param name="calibration_file_path" value="$(find mybot_hardware)/config" />
        <param name="calibration_file_name" value="imu0" />
        <param name="frame_id" value="imu_link" />
        <param name="topic_name" value="imu0/data" />
        <param name="update_rate" value="10" />
    </node>
```

https://github.com/kulbu/kulbu_hardware/blob/1a43e55225464049cbcbfc1f1b15f5b4af12e5ab/launch/imu.launch
