### ISSUE TITLE
RTIMULib

### ISSUE THREAD

**Issue by mryellow** [romainreignier/rtimulib_ros#3]
It moved to https://github.com/RTIMULib/RTIMULib

Now it's vanished..... wtf

**Comment by romainreignier** [comment]
Ah yes, sadly.
For now, it is still working for the current IMU supported.

**Comment by mryellow** [comment]
Decent fork tree here:

https://github.com/rgwave/RTIMULib
https://github.com/tmolteno/RTIMULib
https://github.com/mryellow/RTIMULib

**Comment by romainreignier** [comment]
RTIMULib is still here: https://github.com/richards-tech/RTIMULib
And the development version is here: https://github.com/richards-tech/RTIMULib2 (need to be tested).
