### ISSUE TITLE
libRTIMULib.so.7

### ISSUE THREAD

**Issue by yueshukun** [romainreignier/rtimulib_ros#7]
hello,
    When I used "roslaunch rtimulib_ros rtimulib_ros.launch",it occured the following question:
    /home/test/vins_ws/devel/lib/rtimulib_ros/rtimulib_ros: error while loading shared libraries:   libRTIMULib.so.7: cannot open shared object file: No such file or directory
    Could you tell me how to solve this question.Thanks!

**Comment by romainreignier** [comment]
Hello,
It seems that the RTIMULib is not installed on your computer. So please, make sure you follow these indications first: https://github.com/RTIMULib/RTIMULib/tree/master/Linux#build-using-cmake

**Comment by yueshukun** [comment]
According to your link, I completed it,but I encountered the following question,do you know how to solve it?Thanks.
"Failed to open I2C port - Failed to read fifo count
Failed to open I2C bus 0"

**Comment by romainreignier** [comment]
The message says that it failed to open the device `/dev/i2c0`.
Please make sure that you have enable the i2c device of your board and loaded the Linux `i2c-dev` module.
If your i2c device is not the `0` change the `I2CBus` entry in the configuration file.
Did you managed to calibrate your IMU as explained here: https://github.com/romainreignier/rtimulib_ros#calibration ?

**Comment by yueshukun** [comment]
@romainreignier Sorry, I want to ask you another question.My imu is mpu9250/6500,and I use it on Arduino uno board.Can I use imu with rtimulib_ros,and how can I do that.
    I'm so sorry taht I really don't know about it.Thanks!

**Comment by romainreignier** [comment]
No, you cannot use it.
This node can only be used on a Linux board that has an i2c port (like a Raspberry Pi) so you directly connect the IMU to the computer.
When using an Arduino, you need to write (or find) another node.

**Comment by yueshukun** [comment]
Thanks, I got it.

**Comment by Colidar** [comment]
@yueshukun 
did you find a node which works with arduino? I'm also looking for one!!

**Comment by romainreignier** [comment]
You could use [RTIMULib-Arduino](https://github.com/RTIMULib/RTIMULib-Arduino) and [rosserial](https://github.com/ros-drivers/rosserial).

**Comment by Colidar** [comment]
Thanks! I will try it
